version: "3.8"  # 사용할 Docker Compose 파일 버전

services:
  mysql:    # 서비스 이름 (내부적으로 이 이름으로 컨테이너 식별)
    container_name: saju_nodejs_mysql   # 실제 생성될 컨테이너 이름
    image: mysql:5.7.27     # 사용할 MySQL 이미지 (5.7.27 버전)
    platform: linux/amd64   # ARM 서버에서도 실행할 수 있도록 AMD64로 강제 설정
    #restart: always        # 컨테이너가 비정상 종료되면 항상 재시작

    environment:                    # MySQL 실행 시 필요한 환경 변수 설정
      - MYSQL_USER=root             # 추가 사용자 이름 (root와 동일하게 설정되어 있음)
      - MYSQL_PASSWORD=1234         # MYSQL_USER 의 비밀번호
      - MYSQL_ROOT_PASSWORD=1234    # 루트 계정의 비밀번호
      - MYSQL_DATABASE=saju_db_dev  # 컨테이너가 시작될 때 생성할 초기 데이터베이스 이름
      - MYSQL_SSL_DISABLED          # SSL 비활성화 (빈 값이지만 설정 시 SSL 기능이 꺼짐)
      - TZ=Asia/Seoul               # 타임존 설정 (한국 시간)

    ports:
      - "3309:3306"   # 호스트의 3309 포트를 컨테이너의 3306 포트(MySQL 기본 포트)로 매핑

    volumes:
      - ./mysql/mysql_data:/var/lib/mysql   # MySQL 데이터를 로컬 디렉토리에 저장하여 데이터 영속성 확보

    # MySQL 실행시 추가 커맨드
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"          # 기본 문자셋을 utf8mb4로 설정 (이모지 포함 지원)
      - "--collation-server=utf8mb4_unicode_ci"   # 정렬 기준 설정 (국제 유니코드 표준)

